apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  namespace: infra-prometheus
spec:
  project: default
  source:
    repoURL: https://github.com/antjpar/minikube-dev-env.git
    path: /infra/prometheus
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
